algoritmo "MÉDIA"

var

  nota1, nota2, nota3: real
  resultado: real
  
  
inicio

escreva

 escreval ("Digite sua 1 primeira nota:")
 leia(nota1)
 
 escreval("")

 

  escreval("Digite sua 2 segunda nota:")
  leia(nota2)

 escreval("")
 
   escreval ("Digite sua 3 terceira nota:")
  leia(nota3)

 escreval("")
 
 resultado <- nota1 + nota2 + nota3/3
 
escreval  ("A média da sua nota é:", resultado, "pts")
 
 
fimalgoritmo

 
 

